services:
  # Express API service
  gatherly-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://gatherly:dev_password@postgres:5432/gatherly_dev
      - REDIS_URL=redis://redis:6379
    volumes:
      # Mount source code for hot reloading in development
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      # Exclude node_modules from mounting
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - gatherly-network
    profiles:
      - service

  # Infrastructure services
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: gatherly_dev
      POSTGRES_USER: gatherly
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gatherly-network
    profiles:
      - infrastructure
      - service

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - gatherly-network  
    profiles:
      - infrastructure
      - service

networks:
  gatherly-network:
    driver: bridge

volumes:
  postgres_data: